FROM alpine:3.18

RUN apk add --no-cache curl unzip
#pake ngrok versi 3
RUN curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o /tmp/ngrok.tgz \
    && tar -xzf /tmp/ngrok.tgz -C /usr/local/bin/ \
    && chmod +x /usr/local/bin/ngrok \
    && rm /tmp/ngrok.tgz

ENTRYPOINT ["ngrok"]

