apiVersion: v1
kind: Service
metadata:
  name: {{ include "pena-app.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "pena-app.name" . }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.appSelector | default "my-nodejs-chart" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
