apiVersion: v1
kind: Service
metadata:
  name: {{ include "pena-app.fullname" . }}
  labels:
    app: {{ include "pena-app.name" . }}  # WAJIB agar ServiceMonitor bisa nemukan service ini
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http                          # WAJIB agar ServiceMonitor bisa scrape port ini
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "pena-app.name" . }}
